// Comprehensive UK & worldwide model lists per make.
// Includes generations, performance variants, EVs, classics and heritage models.
// Not exhaustive — but covers the vast majority of cars a UK private seller will list.
// If a make isn't here, the form falls back to a free-text input.

export const CAR_MODELS: Record<string, string[]> = {
  "AC": ["Cobra", "Aceca", "428", "ACE"],
  "Abarth": ["500", "595", "595 Competizione", "695", "695 Biposto", "124 Spider", "Punto Evo"],
  "Acura": ["NSX", "Integra", "TL", "TSX", "RDX", "MDX"],
  "Alfa Romeo": ["Giulia", "Giulia Quadrifoglio", "Giulietta", "Stelvio", "Stelvio Quadrifoglio", "Tonale", "MiTo", "159", "156", "147", "Brera", "GT", "GTV", "Spider", "33", "75", "8C Competizione", "4C", "Junior"],
  "Alpine": ["A110", "A110 S", "A110 GT", "A310", "A610"],
  "Ariel": ["Atom", "Nomad", "Hipercar"],
  "Aston Martin": ["DB7", "DB9", "DB11", "DB12", "Vantage", "V8 Vantage", "V12 Vantage", "Vanquish", "DBS", "DBS Superleggera", "DBX", "DBX 707", "Rapide", "Virage", "Cygnet", "One-77", "Valkyrie", "Valhalla"],
  "Audi": ["A1", "A2", "A3", "A4", "A4 Allroad", "A5", "A6", "A6 Allroad", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q5 Sportback", "Q6 e-tron", "Q7", "Q8", "Q8 e-tron", "TT", "TTS", "TT RS", "R8", "e-tron", "e-tron GT", "S1", "S3", "S4", "S5", "S6", "S7", "S8", "RS3", "RS4", "RS5", "RS6", "RS7", "RS Q3", "RS Q8", "Coupe Quattro", "80", "100", "200"],
  "Austin": ["Mini", "Mini Cooper", "Mini Cooper S", "Metro", "Allegro", "Maxi", "Princess", "Montego", "Maestro", "1100", "1300", "Healey 3000"],
  "Austin-Healey": ["Sprite", "100", "3000"],
  "BAC": ["Mono"],
  "Bentley": ["Continental GT", "Continental GT Speed", "Continental GTC", "Flying Spur", "Bentayga", "Bentayga EWB", "Mulsanne", "Brooklands", "Arnage", "Azure", "Turbo R", "Eight"],
  "BMW": ["1 Series", "2 Series", "2 Series Active Tourer", "2 Series Gran Coupe", "3 Series", "3 Series Touring", "4 Series", "4 Series Gran Coupe", "5 Series", "5 Series Touring", "6 Series", "6 Series GT", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z1", "Z3", "Z4", "Z8", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX2", "iX3", "M2", "M3", "M3 Touring", "M4", "M5", "M5 Touring", "M6", "M8", "M135i", "M140i", "M235i", "M240i", "M340i", "M440i", "M550i", "M850i", "X3 M", "X4 M", "X5 M", "X6 M"],
  "Bristol": ["Blenheim", "Fighter", "Britannia", "411"],
  "Bugatti": ["Veyron", "Chiron", "Chiron Super Sport", "Chiron Pur Sport", "Divo", "Centodieci", "Mistral", "Tourbillon", "EB110"],
  "Buick": ["Regal", "LaCrosse", "Enclave", "Envision", "Skylark", "Riviera", "Roadmaster", "Wildcat"],
  "BYD": ["Atto 3", "Dolphin", "Seal", "Seal U", "Han", "Tang", "Sealion 7"],
  "Cadillac": ["Escalade", "CTS", "CTS-V", "ATS", "ATS-V", "STS", "XTS", "CT4", "CT5", "CT6", "XT4", "XT5", "XT6", "Eldorado", "Seville", "DeVille", "Lyriq"],
  "Caterham": ["Seven 170", "Seven 270", "Seven 340", "Seven 360", "Seven 420", "Seven 485", "Seven 620"],
  "Chevrolet": ["Aveo", "Cruze", "Captiva", "Spark", "Camaro", "Camaro ZL1", "Camaro Z28", "Corvette", "Corvette C5", "Corvette C6", "Corvette C7", "Corvette C8", "Corvette Z06", "Corvette ZR1", "Impala", "Malibu", "Bel Air", "Suburban", "Tahoe", "Silverado", "Colorado", "Trailblazer", "Blazer", "Equinox", "Bolt EV", "Volt", "El Camino", "Nova"],
  "Chrysler": ["300", "300C", "Grand Voyager", "Voyager", "Crossfire", "PT Cruiser", "Sebring", "Pacifica", "Town & Country"],
  "Citroën": ["AX", "Saxo", "C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Cactus", "C4 Picasso", "C4 X", "C5", "C5 Aircross", "C5 X", "C6", "C8", "Berlingo", "Spacetourer", "Dispatch", "Relay", "DS3", "DS4", "DS5", "Xsara", "Xsara Picasso", "Xantia", "ZX", "BX", "CX", "2CV", "DS", "SM", "Traction Avant"],
  "Cupra": ["Born", "Formentor", "Leon", "Leon Sportstourer", "Ateca", "Tavascan", "Terramar"],
  "Dacia": ["Sandero", "Sandero Stepway", "Duster", "Jogger", "Spring", "Logan", "Lodgy", "Bigster"],
  "Daewoo": ["Matiz", "Lanos", "Nubira", "Leganza", "Tacuma", "Kalos"],
  "Daihatsu": ["Charade", "Cuore", "Sirion", "Terios", "Copen", "Materia"],
  "Datsun": ["240Z", "260Z", "280Z", "Sunny", "Cherry", "Bluebird"],
  "DeLorean": ["DMC-12"],
  "Dodge": ["Challenger", "Challenger Hellcat", "Challenger Demon", "Charger", "Charger Hellcat", "Viper", "Durango", "Ram", "Caliber", "Avenger", "Journey", "Nitro", "Magnum", "Dart"],
  "DS Automobiles": ["DS 3", "DS 3 Crossback", "DS 4", "DS 5", "DS 7 Crossback", "DS 9"],
  "Ferrari": ["Roma", "Roma Spider", "Portofino", "Portofino M", "California", "California T", "F8 Tributo", "F8 Spider", "488 GTB", "488 Pista", "488 Spider", "458 Italia", "458 Speciale", "458 Spider", "F430", "360 Modena", "550 Maranello", "575M Maranello", "599 GTB", "599 GTO", "612 Scaglietti", "FF", "GTC4Lusso", "812 Superfast", "812 GTS", "812 Competizione", "296 GTB", "296 GTS", "SF90 Stradale", "SF90 Spider", "SF90 XX", "Purosangue", "LaFerrari", "Enzo", "Daytona SP3", "F40", "F50", "Testarossa", "Mondial", "308 GTB", "328 GTB", "348", "Dino"],
  "Fiat": ["500", "500 Abarth", "500X", "500L", "500e", "Panda", "Panda 4x4", "Tipo", "Punto", "Grande Punto", "Punto Evo", "Doblo", "Bravo", "Stilo", "Croma", "Multipla", "Coupe", "Barchetta", "124 Spider", "Uno", "Cinquecento", "Seicento"],
  "Fisker": ["Karma", "Ocean"],
  "Ford": ["Fiesta", "Fiesta ST", "Focus", "Focus ST", "Focus RS", "Puma", "Puma ST", "Kuga", "EcoSport", "Mondeo", "Mondeo ST", "Mustang", "Mustang Mach-E", "Mustang GT", "Mustang Shelby GT500", "S-Max", "Galaxy", "C-Max", "B-Max", "Ranger", "Ranger Raptor", "Transit", "Transit Custom", "Tourneo Custom", "Tourneo Connect", "Edge", "Ka", "Ka+", "Capri", "Capri (2024)", "Sierra", "Sierra Cosworth", "Escort", "Escort Cosworth", "Cortina", "Granada", "GT", "GT40", "Bronco", "Explorer", "F-150", "F-150 Raptor", "F-150 Lightning", "Maverick"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80", "Electrified G80", "Electrified GV70"],
  "Ginetta": ["G40", "G55", "G60", "Akula"],
  "GMC": ["Sierra", "Yukon", "Acadia", "Terrain", "Hummer EV"],
  "Honda": ["Jazz", "Jazz Crosstar", "Civic", "Civic Type R", "Civic Type R FK2", "Civic Type R FK8", "Civic Type R FL5", "HR-V", "CR-V", "ZR-V", "e", "e:Ny1", "Accord", "Accord Type R", "Insight", "Legend", "Prelude", "S2000", "Integra", "Integra Type R", "NSX", "NSX (2017)", "CRX", "Logo", "FR-V", "Stream"],
  "Hyundai": ["i10", "i20", "i20 N", "i30", "i30 N", "i40", "Bayon", "Kona", "Kona Electric", "Kona N", "Tucson", "Santa Fe", "Ioniq", "Ioniq 5", "Ioniq 5 N", "Ioniq 6", "Ioniq 9", "Inster", "Nexo", "Veloster", "Veloster N", "Genesis Coupe", "Getz", "Accent", "Coupe"],
  "Infiniti": ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX70", "QX80", "FX35", "FX37", "FX50", "G37"],
  "Jaguar": ["XE", "XE SV Project 8", "XF", "XJ", "XJ220", "XJR", "XK", "XKR", "XKR-S", "XK8", "F-Type", "F-Type R", "F-Type SVR", "F-Pace", "F-Pace SVR", "E-Pace", "I-Pace", "S-Type", "X-Type", "Sovereign", "Mark 2", "E-Type", "D-Type", "C-X75"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Grand Cherokee SRT", "Grand Cherokee Trackhawk", "Wrangler", "Wrangler Rubicon", "Avenger", "Patriot", "Commander", "Gladiator"],
  "Jensen": ["Interceptor", "FF", "GT"],
  "Kia": ["Picanto", "Rio", "Stonic", "Ceed", "Ceed GT", "ProCeed", "XCeed", "Soul", "Sportage", "Niro", "Niro EV", "Sorento", "EV3", "EV6", "EV6 GT", "EV9", "Stinger", "Stinger GT", "Carens", "Optima", "Venga"],
  "Koenigsegg": ["CCX", "Agera", "Agera RS", "One:1", "Regera", "Jesko", "Gemera"],
  "Lada": ["Niva", "Riva", "Samara", "Vesta"],
  "Lamborghini": ["Huracán", "Huracán Performante", "Huracán STO", "Huracán Tecnica", "Huracán Sterrato", "Aventador", "Aventador SVJ", "Aventador SV", "Urus", "Urus Performante", "Urus SE", "Revuelto", "Temerario", "Gallardo", "Gallardo Superleggera", "Murciélago", "Murciélago LP670 SV", "Diablo", "Countach", "Countach LPI 800-4", "Miura", "Espada", "Jalpa", "Sián"],
  "Lancia": ["Delta", "Delta Integrale", "Stratos", "Fulvia", "Beta", "Thema", "Ypsilon", "037"],
  "Land Rover": ["Defender", "Defender 90", "Defender 110", "Defender 130", "Defender (Classic)", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Sport SVR", "Range Rover Velar", "Range Rover Evoque", "Freelander", "Freelander 2", "Series I", "Series II", "Series III"],
  "Leapmotor": ["T03", "C10"],
  "Lexus": ["CT", "IS", "IS-F", "ES", "GS", "GS-F", "LS", "UX", "NX", "RX", "RZ", "LBX", "LC", "LC 500", "LFA", "RC", "RC F", "SC430"],
  "Lincoln": ["Navigator", "Continental", "MKZ", "MKX", "Aviator", "Town Car"],
  "Lotus": ["Elise", "Elise S1", "Elise S2", "Elise S3", "Elise Cup", "Exige", "Exige S", "Exige Sport 410", "Evora", "Evora 400", "Evora GT430", "Emira", "Eletre", "Emeya", "Esprit", "Esprit V8", "Europa", "Elan", "Carlton", "Seven", "340R", "2-Eleven", "3-Eleven", "Evija"],
  "Lucid": ["Air", "Gravity"],
  "Marcos": ["Mantis", "GT"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20", "MC20 Cielo", "MC12", "GranTurismo", "GranTurismo Folgore", "GranCabrio", "3200 GT", "4200 GT", "Coupe", "Spyder", "Bora", "Merak", "Khamsin", "Mistral", "Biturbo"],
  "Maybach": ["57", "62", "S-Class", "GLS"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda3 MPS", "Mazda5", "Mazda6", "Mazda6 MPS", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "CX-90", "MX-5", "MX-5 RF", "MX-30", "RX-7", "RX-8", "323", "626", "929", "Premacy", "Tribute", "BT-50"],
  "McLaren": ["540C", "570S", "570S Spider", "570GT", "600LT", "620R", "650S", "675LT", "720S", "720S Spider", "750S", "765LT", "Artura", "GT", "GTS", "Speedtail", "Senna", "Senna GTR", "Elva", "P1", "F1", "12C", "Solus GT", "750LT", "W1"],
  "Mercedes-AMG": ["A 35", "A 45", "C 43", "C 63", "C 63 S", "E 53", "E 63", "E 63 S", "S 63", "GLA 35", "GLA 45", "GLC 43", "GLC 63", "GLE 53", "GLE 63", "GT", "GT 63", "GT 4-Door", "ONE", "SLS", "SL 55", "SL 63"],
  "Mercedes-Benz": ["A-Class", "A-Class Saloon", "B-Class", "C-Class", "C-Class Estate", "C-Class Coupe", "C-Class Cabriolet", "CLA", "CLA Shooting Brake", "CLS", "CLK", "E-Class", "E-Class Estate", "E-Class Coupe", "E-Class Cabriolet", "S-Class", "S-Class Coupe", "GLA", "GLB", "GLC", "GLC Coupe", "GLE", "GLE Coupe", "GLS", "G-Class", "SL", "SLC", "SLK", "SLR McLaren", "AMG GT", "AMG GT 4-Door", "EQA", "EQB", "EQC", "EQE", "EQE SUV", "EQS", "EQS SUV", "EQV", "V-Class", "Vito", "Sprinter", "Citan", "Maybach S-Class", "190E", "190E Cosworth", "300SL", "Pagoda", "W124", "W126", "W140"],
  "MG": ["MG3", "MG4", "MG4 XPower", "MG5", "MG5 EV", "ZS", "ZS EV", "HS", "HS PHEV", "Cyberster", "MGB", "MGB GT", "MGA", "Midget", "MGF", "TF", "ZR", "ZS (Mk1)", "ZT", "Maestro", "Montego", "Metro"],
  "Mini (Classic)": ["Cooper", "Cooper S", "Mini 1000", "Mini City", "Mini Mayfair", "Mini Cooper Sport"],
  "MINI": ["Hatch (3-door)", "Hatch (5-door)", "Cooper", "Cooper S", "John Cooper Works", "Convertible", "Clubman", "Countryman", "Aceman", "Electric", "Cooper SE", "Paceman", "Coupe", "Roadster"],
  "Mitsubishi": ["Mirage", "Colt", "ASX", "Outlander", "Outlander PHEV", "Eclipse Cross", "L200", "Shogun", "Shogun Sport", "Lancer", "Lancer Evo VI", "Lancer Evo VII", "Lancer Evo VIII", "Lancer Evo IX", "Lancer Evo X", "FTO", "GTO", "3000GT", "Galant", "i-MiEV"],
  "Morgan": ["Plus 4", "Plus 6", "Plus 8", "Roadster", "Aero 8", "3 Wheeler", "Super 3"],
  "Morris": ["Minor", "Marina", "Ital", "Oxford", "Mini"],
  "Nio": ["ET5", "ET7", "EL6", "EL7"],
  "Nissan": ["Micra", "Note", "Pulsar", "Almera", "Juke", "Juke Nismo", "Qashqai", "X-Trail", "Murano", "Pathfinder", "Leaf", "Ariya", "Navara", "350Z", "370Z", "370Z Nismo", "Z (2023)", "GT-R", "GT-R Nismo", "Skyline GT-R R32", "Skyline GT-R R33", "Skyline GT-R R34", "Silvia S13", "Silvia S14", "Silvia S15", "200SX", "300ZX", "Patrol", "Cube", "NV200", "Primera"],
  "Noble": ["M12", "M400", "M600"],
  "Pagani": ["Zonda", "Huayra", "Huayra Roadster", "Utopia"],
  "Peugeot": ["106", "107", "108", "205", "205 GTI", "206", "206 GTI", "207", "208", "208 GTI", "2008", "e-208", "306", "307", "308", "308 GT", "308 GTI", "3008", "407", "408", "508", "508 PSE", "5008", "607", "807", "1007", "Rifter", "Partner", "Expert", "Boxer", "Traveller", "RCZ", "RCZ R", "e-2008", "e-308", "e-3008"],
  "Pininfarina": ["Battista"],
  "Plymouth": ["Barracuda", "Cuda", "Road Runner", "Prowler", "GTX"],
  "Polestar": ["1", "2", "3", "4", "5", "6"],
  "Pontiac": ["GTO", "Firebird", "Trans Am", "Solstice", "G8"],
  "Porsche": ["911", "911 Carrera", "911 Carrera S", "911 Carrera 4", "911 Targa", "911 Turbo", "911 Turbo S", "911 GT3", "911 GT3 RS", "911 GT2", "911 GT2 RS", "911 Dakar", "911 Sport Classic", "911 (964)", "911 (993)", "911 (996)", "911 (997)", "911 (991)", "911 (992)", "718 Cayman", "718 Cayman GT4", "718 Cayman GT4 RS", "718 Boxster", "718 Boxster Spyder", "718 Spyder RS", "Cayman", "Boxster", "Panamera", "Panamera Turbo", "Panamera GTS", "Macan", "Macan GTS", "Macan Turbo", "Macan Electric", "Cayenne", "Cayenne S", "Cayenne GTS", "Cayenne Turbo", "Cayenne Coupe", "Taycan", "Taycan 4S", "Taycan Turbo", "Taycan Turbo S", "Taycan Cross Turismo", "918 Spyder", "Carrera GT", "959", "928", "944", "944 Turbo", "968", "924"],
  "RAM": ["1500", "2500", "TRX"],
  "Reliant": ["Robin", "Rialto", "Scimitar"],
  "Renault": ["Twingo", "Clio", "Clio RS 172", "Clio RS 182", "Clio RS 197", "Clio RS 200", "Clio RS 220 Trophy", "Clio Williams", "Captur", "Megane", "Megane RS 225", "Megane RS 250", "Megane RS 265 Trophy", "Megane RS 275 Trophy-R", "Megane RS 280", "Megane RS 300 Trophy", "Megane E-Tech", "Scenic", "Scenic E-Tech", "Grand Scenic", "Kadjar", "Arkana", "Austral", "Espace", "Zoe", "Trafic", "Master", "Kangoo", "5", "5 GT Turbo", "5 (E-Tech)", "4", "4L", "Sport Spider", "Avantime", "Vel Satis", "Laguna", "Safrane", "Twizy", "Wind", "Alpine A610"],
  "Rimac": ["Concept One", "Nevera"],
  "Rivian": ["R1T", "R1S"],
  "Rolls-Royce": ["Ghost", "Ghost Black Badge", "Phantom", "Phantom Drophead", "Wraith", "Dawn", "Cullinan", "Spectre", "Silver Shadow", "Silver Spirit", "Silver Seraph", "Corniche", "Camargue", "Silver Cloud", "Silver Wraith"],
  "Rover": ["25", "45", "75", "100", "200", "400", "600", "800", "Streetwise", "SD1", "P5", "P6", "Mini"],
  "Saab": ["9-3", "9-3 Aero", "9-3 Convertible", "9-5", "9-5 Aero", "900", "900 Turbo", "9000", "9-2X", "9-7X"],
  "SEAT": ["Mii", "Ibiza", "Ibiza Cupra", "Leon", "Leon Cupra", "Leon Cupra R", "Arona", "Ateca", "Tarraco", "Alhambra", "Toledo", "Altea", "Exeo"],
  "Singer": ["911 Reimagined", "DLS", "Turbo Study"],
  "Škoda": ["Citigo", "Fabia", "Fabia vRS", "Scala", "Octavia", "Octavia vRS", "Octavia Estate", "Superb", "Superb Estate", "Kamiq", "Karoq", "Kodiaq", "Kodiaq vRS", "Enyaq", "Enyaq Coupe", "Yeti", "Roomster", "Rapid", "Felicia"],
  "Smart": ["Fortwo", "Fortwo Cabrio", "Forfour", "Roadster", "#1", "#3", "#5"],
  "Spyker": ["C8", "D8"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso", "Rodius", "Kyron"],
  "Subaru": ["Impreza", "Impreza WRX", "Impreza WRX STI", "Forester", "Outback", "Legacy", "XV", "Crosstrek", "BRZ", "Levorg", "Solterra", "Tribeca", "Justy", "SVX", "22B"],
  "Sunbeam": ["Tiger", "Alpine", "Rapier"],
  "Suzuki": ["Alto", "Celerio", "Swift", "Swift Sport", "Ignis", "Baleno", "Vitara", "S-Cross", "Jimny", "Across", "SX4", "Wagon R", "Cappuccino"],
  "Talbot": ["Sunbeam", "Solara", "Horizon", "Samba"],
  "Tata": ["Nexon", "Tigor", "Indica"],
  "Tesla": ["Model 3", "Model 3 Performance", "Model S", "Model S Plaid", "Model X", "Model X Plaid", "Model Y", "Model Y Performance", "Cybertruck", "Roadster", "Roadster (2026)"],
  "Toyota": ["Aygo", "Aygo X", "Yaris", "Yaris Cross", "Yaris GR", "GR Yaris", "Corolla", "Corolla Touring Sports", "Camry", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Land Cruiser Prado", "Prius", "Prius+", "Mirai", "GR86", "GR Supra", "Supra Mk4", "MR2", "MR2 Mk1", "MR2 Mk2", "MR2 Mk3", "Celica", "Celica GT-Four", "Carina", "Avensis", "Verso", "iQ", "bZ4X", "Hilux", "Hilux Invincible", "Proace", "Proace City", "FJ Cruiser", "Crown", "AE86"],
  "Triumph": ["Spitfire", "GT6", "TR4", "TR5", "TR6", "TR7", "TR8", "Stag", "Dolomite", "Dolomite Sprint", "Herald", "2000", "2500", "Vitesse", "Acclaim"],
  "TVR": ["Chimaera", "Griffith", "Cerbera", "Tuscan", "Tamora", "T350", "Sagaris", "Tasmin"],
  "Vauxhall": ["Corsa", "Corsa-e", "Corsa VXR", "Astra", "Astra GTC", "Astra VXR", "Insignia", "Insignia VXR", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro", "Movano", "Adam", "Viva", "Meriva", "Zafira", "Zafira Tourer", "Antara", "Vectra", "VXR8", "Monaro", "Cavalier", "Carlton", "Carlton Lotus", "Frontera", "Tigra", "Calibra", "Nova", "Chevette"],
  "VinFast": ["VF 6", "VF 7", "VF 8", "VF 9"],
  "Volkswagen": ["up!", "e-up!", "Polo", "Polo GTI", "Polo R WRC", "Golf", "Golf GTI", "Golf GTI Clubsport", "Golf R", "Golf R32", "Golf TDI", "Golf Estate", "Golf Plus", "Jetta", "Passat", "Passat Estate", "Passat CC", "Arteon", "Arteon Shooting Brake", "Scirocco", "Scirocco R", "Eos", "Beetle", "New Beetle", "T-Cross", "T-Roc", "T-Roc R", "Tiguan", "Tiguan Allspace", "Touareg", "Touareg R", "Atlas", "ID.3", "ID.4", "ID.5", "ID.7", "ID.7 Tourer", "ID.Buzz", "Caddy", "Transporter", "Transporter T5", "Transporter T6", "Transporter T6.1", "Caravelle", "Touran", "Sharan", "Phaeton", "Lupo", "Fox", "Bora", "Corrado", "Karmann Ghia"],
  "Volvo": ["S40", "S60", "S60 Polestar", "S80", "S90", "V40", "V40 Cross Country", "V50", "V60", "V60 Polestar", "V70", "V70 R", "V90", "V90 Cross Country", "XC40", "XC40 Recharge", "XC60", "XC70", "XC90", "EX30", "EX40", "EX90", "C30", "C40", "C70", "850", "850 T-5R", "240", "740", "940", "960", "Amazon", "P1800"],
  "Wiesmann": ["MF3", "MF4", "MF5", "Project Thunderball"],
  "XPeng": ["P7", "G6", "G9"],
  "Zenvo": ["ST1", "TSR-S", "Aurora"],
};

export function getModelsForMake(make: string): string[] {
  return CAR_MODELS[make] || [];
}
