// Curated UK model lists per make. Not exhaustive — covers the most common private-sale models.
export const CAR_MODELS: Record<string, string[]> = {
  "Abarth": ["500", "595", "695", "124 Spider"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Stelvio", "Tonale", "MiTo", "159", "Brera"],
  "Aston Martin": ["DB9", "DB11", "DB12", "Vantage", "DBS", "DBX", "Rapide"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "Q4 e-tron", "S3", "S4", "S5", "RS3", "RS4", "RS6"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "i5", "i7", "iX", "iX1", "iX3", "M2", "M3", "M4", "M5"],
  "Chevrolet": ["Aveo", "Cruze", "Captiva", "Spark", "Camaro", "Corvette"],
  "Chrysler": ["300C", "Grand Voyager", "Crossfire"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5", "C5 Aircross", "C5 X", "Berlingo", "DS3", "DS4", "DS5"],
  "Cupra": ["Born", "Formentor", "Leon", "Ateca", "Tavascan"],
  "Dacia": ["Sandero", "Duster", "Jogger", "Spring", "Logan"],
  "DS Automobiles": ["DS 3", "DS 4", "DS 7", "DS 9"],
  "Ferrari": ["Roma", "Portofino", "F8 Tributo", "296 GTB", "SF90", "812 Superfast", "Purosangue", "California"],
  "Fiat": ["500", "500X", "500L", "500e", "Panda", "Tipo", "Punto", "Doblo"],
  "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "EcoSport", "Mondeo", "Mustang", "Mustang Mach-E", "S-Max", "Galaxy", "Ranger", "Transit", "Tourneo", "Edge", "Ka+"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "Honda": ["Jazz", "Civic", "HR-V", "CR-V", "ZR-V", "e", "e:Ny1", "Accord"],
  "Hyundai": ["i10", "i20", "i30", "Bayon", "Kona", "Tucson", "Santa Fe", "Ioniq", "Ioniq 5", "Ioniq 6"],
  "Infiniti": ["Q30", "Q50", "Q60", "QX30", "QX70"],
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "F-Pace", "E-Pace", "I-Pace"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  "Kia": ["Picanto", "Rio", "Ceed", "ProCeed", "XCeed", "Stonic", "Sportage", "Niro", "Sorento", "EV6", "EV9", "Soul"],
  "Lamborghini": ["Huracán", "Aventador", "Urus", "Revuelto"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Freelander"],
  "Lexus": ["CT", "IS", "ES", "LS", "UX", "NX", "RX", "LC", "RZ", "LBX"],
  "Lotus": ["Elise", "Exige", "Evora", "Emira", "Eletre"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20", "GranTurismo"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  "McLaren": ["570S", "600LT", "720S", "750S", "Artura", "GT", "765LT"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "SL", "SLC", "AMG GT", "EQA", "EQB", "EQC", "EQE", "EQS", "V-Class", "Vito"],
  "MG": ["MG3", "MG4", "MG5", "ZS", "HS", "Cyberster"],
  "MINI": ["Hatch", "Cooper", "Convertible", "Clubman", "Countryman", "Aceman", "Electric"],
  "Mitsubishi": ["Mirage", "ASX", "Outlander", "Eclipse Cross", "L200", "Shogun"],
  "Nissan": ["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Navara", "370Z", "GT-R"],
  "Peugeot": ["108", "208", "2008", "308", "3008", "408", "508", "5008", "Rifter", "Partner", "e-208", "e-2008"],
  "Polestar": ["1", "2", "3", "4"],
  "Porsche": ["911", "718 Cayman", "718 Boxster", "Panamera", "Macan", "Cayenne", "Taycan"],
  "Renault": ["Clio", "Captur", "Megane", "Megane E-Tech", "Scenic", "Kadjar", "Arkana", "Austral", "Zoe", "Twingo", "Trafic"],
  "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Dawn", "Cullinan", "Spectre"],
  "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Mii"],
  "Škoda": ["Citigo", "Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  "Smart": ["Fortwo", "Forfour", "#1", "#3"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso"],
  "Subaru": ["Impreza", "Forester", "Outback", "XV", "BRZ", "Levorg"],
  "Suzuki": ["Swift", "Ignis", "Baleno", "Vitara", "S-Cross", "Jimny", "Across"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  "Toyota": ["Aygo", "Aygo X", "Yaris", "Yaris Cross", "Corolla", "Camry", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Prius", "GR Yaris", "GR86", "Supra", "bZ4X", "Hilux", "Proace"],
  "Vauxhall": ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro", "Adam", "Viva"],
  "Volkswagen": ["up!", "Polo", "Golf", "Golf GTI", "Golf R", "Passat", "Arteon", "T-Cross", "T-Roc", "Tiguan", "Touareg", "ID.3", "ID.4", "ID.5", "ID.7", "ID.Buzz", "Caddy", "Transporter", "Touran", "Sharan"],
  "Volvo": ["S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90", "EX30", "EX40", "EX90", "C40"],
};

export function getModelsForMake(make: string): string[] {
  return CAR_MODELS[make] || [];
}
